### PR TITLE
A profile displayer.

### PR DESCRIPTION
**Pull request by K-Kumar-01**
Visiting profiles is good.
But dull profiles obviously make a bad impression.
this is a new type of display.
Using Basic CSS, display profiles as card. 
Just see and tell me how you like it.
One more thing, The contact info there must be icons. I used simple text but they will be icons. 
From font awesome icons.

### CODE REVIEW

**Comment by king-11** [comment]
The current design doesn't go with the present trends of some basic features a profile card should include. I really liked the animation but there needs to be an image of the person and the about us can be displayed by either on hover or maybe a more elegant manner you can think of

**Comment by king-11** [comment]
you can also have a look at some of the designs I have added for profile cards. Also, your repo isn't is behind the master branch so please run following commands : 
`git remote add upstream https://github.com/king-11/Web_Design.git`
`git pull upstream master`

 Add your project without the New Ideas folder just include the project folder as per the contributing guidelines.

**Comment by K-Kumar-01** [comment]
The about us is displayed on hover on desktops. On mobiles it wont as hovering on mobiles makes no sense.
For the branch i will see.
Should i continue developments in this or withdraw?

**Comment by king-11** [comment]
Hovering on desktop is same as clicking on mobile so the hover action ia still visible. And i recommend on starting a new pull request.

**Pull request closed without merging**
